### ISSUE TITLE
Peculiar error with Random.id() in a nested _id field

### ISSUE THREAD

**Issue by JulianKingman** [jagi/meteor-astronomy#166] opened 2015-11-03 18:50 UTC
If I create a schema like this:
````javascript
task = Astro.Class({
    name: 'task',
    collection: tasks,
    fields: {
        array: 'array',
        'array.$._id': {
            type: 'string',
            default: function(){return Random.id();}
        }
});
````
The _id will never settle, it will be different every time you ask for it. Why is that?

**Comment by JulianKingman** [comment] 2015-11-03 19:05
I thought it might be conflicting on client and server, with different IDs, but even when I only give it the default property on the server it still has this issue.

**Comment by jagi** [comment] 2015-11-04 12:37
It works but you have an error in your code. It should be:

```js
Task = Astro.Class({
  name: 'task',
  fields: {
    array: {
        type: 'array',
        default: function() {
            return [];
        }
    },
    'array.$._id': {
      type: 'string',
      default: function() {
        return Random.id();
      }
    }
  }
});

var t = new Task();
t.push('array', {});

t.array[0]._id; // some random id
```

**Comment by GeoffWhatley** [comment] 2015-11-05 03:06
Can confirm this isn't working as expected.
Looking directly at the database, it saves a random id as expected, and this never changes - all good.

However, when the collection is accessed with <Astro.Class>.find(), or findOne(), the _id returned in the nested array *does not* match the one saved in the database - it is regenerated each time. This is easily testable in your example by mapping Task to a collection, and then running

```javascript
console.log(t.array[0]._id); // this will match whats saved to the db, as expected
t.save(); // save it

_.times(3, function() {
  // this will print out 3 different ids, none of which match whats stored
  console.log(Task.findOne().array[0]._id);
});
```

I mean it is easy to work around by changing the field to `arrayId`, for example, but this doesnt solve the issue.

**Comment by jagi** [comment] 2015-11-05 12:49
Ok I see. The problem is with fetching nested data that contains the `_id` field. Why at all are you using the `_id` field for a nested field? Is there a reason for using `_id` instead of just `id`? I will however fix it.

**Comment by jagi** [comment] 2015-11-05 13:55
Fixed. It will be released with the next bug fix version

**Closed** 2015-11-05 13:54 UTC
Labels: bug

**Comment by JulianKingman** [comment] 2015-11-05 17:12
Thanks @jagi. It's easier to remember _id as an index than id, it keeps the naming convention and functionality the same.
