### ISSUE TITLE
Accessing updated object after modification via meteorMethod

### ISSUE THREAD

**Issue by Lukasvo** [jagi/meteor-astronomy#620] opened 2017-06-17 22:13 UTC
Hey jagi,

This is probably a noob question, for which I am sorry...

I have a meteorMethod in which I modify some fields and save the object. Let's take the [rename() method from the documentation](http://jagi.github.io/meteor-astronomy/#meteor-methods--220) as an example. After calling this method from the server, the object is being modified and saved to the database, but that doesn't reflect in the code. I thought it should because it's on the server and I haven't supplied a callback, so the code is synchronous (right?).

```
let user = new User({ firstName: "foo", lastName: "foo" });

// server.js
user.rename('John', 'Smith');
console.log(user.firstName); // -> still "foo", although it was correctly saved in the db
```

Why is this? And how can I acces the modified object?
Thank you so much!

**Comment by lukejagodzinski** [comment] 2017-06-18 08:21
What are you probably looking for is the `user.reload()` method which you have to call after executing the `user.rename()` method. It's because the `rename` method does not cause the original `user` object to be "reloaded" from the database. You have to do it by yourself.

**Comment by Lukasvo** [comment] 2017-06-18 11:57
Damn. I should've known that. Thank you!

However, I must be doing something wrong. The object hasn't changed after calling .reload(), even when I call it in the callback of the method. I'm 100% sure it was persisted to the database (the result from the callback is also an id, as expected). Same problem when calling the method on the client. I'll keep searching and post here when I found what's causing it.

**Comment by lukejagodzinski** [comment] 2017-06-18 12:44
Share the code that is not working then maybe I will be able to help you

**Comment by Lukasvo** [comment] 2017-06-18 20:15
Ok, thanks man. Here's the version where I call from the client:

both
```
const Reservation = Class.create(
	{
		name: 'Reservation',
		collection: new Mongo.Collection('reservations'),
		fields: {
			invoices: {
				type: [Invoice],
				default: [],
			},
		},
	});

const Invoice = Class.create(
	{
		name: 'Invoice',
		fields: {
			invoiceTypeId: {
				type: String
			},
			deadline: {
				type: Date,
			},
		},
	});
```

server
```
Reservation.extend({
    meteorMethods: {
        addInvoice(invoiceTypeId, deadline)
        {
            check(invoiceTypeId, String);
            check(deadline, Date);

            let newInvoice = new Invoice({
                    invoiceTypeId: invoiceTypeId,
                    deadline: deadline,
                });

            this.invoices.push(newInvoice);

            return this.save(); // -> reservation effectively gets persisted to the db, including invoices
        },
    }
});
```
client
```
Template.reservation.events({
	'click .js-book'(event, instance)
		{
			let reservation = Template.currentData();
			reservation.callMethod('addInvoice', "someId", new Date()), (err, result) =>
			{
			    reservation.reload();
			    console.dir(reservation); // -> _id is undefined and invoices is empty
			});
		}
});
```

**Comment by lukejagodzinski** [comment] 2017-06-18 21:37
First of all the default value for the `invoices` field should be:

```js
invoices: {
  type: [Invoice],
  default() { return []; }
}
```

maybe that's a problem. Besides that, did you make sure that you're publishing and subscribing to all necessary data? Your code looks ok.

I'm also not sure how Astronomy will behave when you're passing docs as props of blaze templates (`Template.currentData()`). Try not using it and instead just findOne a doc a check if it solved a problem. From what I remember Blaze has strange behavior of losing info about a class of a doc, when passed as templates' attribute.

**Comment by Lukasvo** [comment] 2017-06-18 22:52
Thanks for pointing out my mistakes. I fixed the default empty array, made sure everything's published and subscribed and tried it out without `Template.currentDate()`, but it's still not working unfortunately.

**Comment by lukejagodzinski** [comment] 2017-06-19 07:54
I don't know if it's a problem with pasting the code here on GitHub but you probably have a bug in an event handler. It shouldn't even run your project with this bug but please make sure that you have the correct amount of parenthesis:

```js
let reservation = Reservation.findOne();
reservation.callMethod('addInvoice', 'someId', new Date(), (err, result) => {
  reservation.reload();
  console.dir(reservation); // -> _id is undefined and invoices is empty
});
```

**Comment by Lukasvo** [comment] 2017-06-19 10:31
Yeah, the parenthesis were the result of copy-pasting indeed.

What I did to test out without `Template.currentData()` was to make a new Reservation and call the method on that directly (because the db is empty until this point). That didn't work. I now tested it again by first saving the new Reservation, getting it from the database with findOne and then calling the method, and now .reload() works! So it works when .save() is updating, but not when it's inserting.

PS: Just to make sure, you made a typo in your previous reply I think. It should've been `type: [Invoice]`, without the 's', right?

**Comment by lukejagodzinski** [comment] 2017-06-19 10:43
> PS: Just to make sure, you made a typo in your previous reply I think. It should've been type: [Invoice], without the 's', right?

Yes you're right. I've fixed it.

> What I did to test out without Template.currentData() was to make a new Reservation and call the method on that directly (because the db is empty until this point). That didn't work. I now tested it again by first saving the new Reservation, getting it from the database with findOne and then calling the method, and now .reload() works!

I've made a reproduction and it works but without using Template.currentData().

> So it works when .save() is updating, but not when it's inserting.

You've only been talking about update operation previously. What effect do you want to achieve on insert?

**Comment by Lukasvo** [comment] 2017-06-19 11:21
Oh, sorry if that wasn't clear.

A user can choose between a list of possible Reservations (= all Astronomy classes that are not inserted in the db yet). My intention was to only insert the reservation that the user chose. So when he clicks on one reservation (.js-book), the "addInvoice" method is being called where an invoice is added to Reservation.invoices and where the Reservation is inserted.

Perhaps I should first insert the Reservation with a new method and add the Invoices afterwards?

**Comment by lukejagodzinski** [comment] 2017-06-19 12:25
I don't understand your use case. But from what I understand you're trying to add an invoice to the reservation that is not yet inserted into DB, which is wrong-  you can't do so. You should probably prepare Meteor method that would insert reservation and invoice in one step. But it's not related to this issue. So I'm closing this as the main issue is solved. It wasn't reflecting changes because you've been passing astronomy document as a template property and Blaze does not behave properly in such situation.

**Closed as completed by lukejagodzinski** 2017-06-19 12:25 UTC
