### ISSUE TITLE
Can't fetch data and return it on server-side?

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#463] opened 2016-07-27 19:01 UTC
I'm experiencing some _very_ odd behavior. I have a Meteor method that basically just does `MyAstroClass.find().fetch()` and returns that data. Yet it never shows up on the client side. If I instead use the regular Mongo collection, `MyItems.find().fetch()` and return that, it works fine.

Furthermore, something seems to get stuck/queued. When I save my code which triggers a Meteor re-build, I see the Astro data get dumped in the server console even though I haven't called the method.

I'm on Meteor 1.4, and using the latest version of Astronomy.

**Comment by lukejagodzinski** [comment] 2016-07-27 19:37
Are you using the `softremove` behavior?

**Comment by ffxsam** [comment] 2016-07-27 19:39
Yep!

**Comment by lukejagodzinski** [comment] 2016-07-28 07:37
so maybe these documents are soft removed and that's why they don't appear?

**Comment by ffxsam** [comment] 2016-07-29 00:40
Nope, they're not soft-removed. Should I try temporarily removing that behavior plugin and see if it fixes it?

**Comment by lukejagodzinski** [comment] 2016-07-29 09:38
You have to create reproduction repository because without that it's hard to tell.

**Comment by ffxsam** [comment] 2016-07-29 13:37
Yep, I knew that was coming next. ;) I hope I can reproduce it in a test project. These things tend to happen in my closed-source projects with 7000+ lines of code, ugh.

I'll get back to you soon. Thanks!

**Comment by rnarayan** [comment] 2016-08-05 02:09
I am getting exactly the same error and the only behavior I am using on user collection is "timestamp".

When I do User.find().fetch() and return in my method, nothing reaches the client though console.log on the server does show that users were selected. 

I had to change my code to Meteor.users().find().fetch() and then on the client, loop over the users to create astronomy User class.

Before you ask :) , it's a big project so I will not be able to share the code.

**Comment by lukejagodzinski** [comment] 2016-08-05 07:36
I've made some tests and it works properly:

``` js
if (Meteor.isServer) {
  Meteor.methods({
    test() {
      return Animal.find().fetch();
    }
  });
}

Meteor.call('test', function(err, animals) {
  console.log(animals);
});
```

It works properly in both cases when method is only defined on the server and if it's defined on the server and client. Closing it until you provide some reproduction.

**Closed as completed by lukejagodzinski** 2016-08-05 07:36 UTC
