### ISSUE TITLE
Confusion re: default values and nested fields

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy#276] opened 2016-02-10 18:24 UTC
I have something like this in my User model fields:

```
    profile: {
      type: "object",
      nested: {
        name: "Profile",
        fields: {
          sendPushNotifications: {
            type: "boolean",
            default: () => true
          }
        }
      }
    },
```

If I create users and find them via, say, `User.findOne()`, `user.profile.sendPushNotifications` == true. If I try something like:

```
User.find({role: "assistant", "profile.sendPushNotifications": true}).count()
```

The value is 0. Looking at the database, I see that profile is an empty object and the default value for sendPushNotifications isn't present. This is OK for returning default values for forms and such, but breaks expectations when I expect the default to persist and to find all assistants to whom I can send pushes.

Do default values not work in nested fields, or is there something else going on here? I've checked the docs but the page on defaults doesn't say one way or the other.

I also just tried:

```
    profile: {
      type: "object",
      nested: {
        name: "Profile",
        fields: {
          sendPushNotifications: "boolean"
        }
      },
      default: () => {sendPushNotifications: true}
    },
```

with the same results. The profile is an empty object when searched via `meteor mongo`.

Thanks.

**Comment by jagi** [comment] 2016-02-10 18:35
That's probably because you've inserted a document with this field being empty before setting a default value. I assume that when you insert a new document and you try to find it, you will find it. However, you probably have to migrate your old documents in the collection.

**Comment by ndarilek** [comment] 2016-02-10 18:41
I wish that were the case. I'm pretty aggressively running `meteor 
reset` during my development process to rule out that and other basic 
errors.

**Comment by jagi** [comment] 2016-02-10 18:53
Ok, so create a reproduction repository so I can check out what's the problem. Most often when reproducing, people find out what was the problem. However, if you will be able to reproduce it I will take a look at the code and maybe find the problem.

**Comment by ndarilek** [comment] 2016-02-10 19:50
https://github.com/ndarilek/meteor-astronomy-nested-failure

This behaves somewhat differently. Admittedly I don't call the fields on 
the created objects to see whether they return the default values, but I 
tried 4 separate combinations of setting embedded defaults with subtle 
differences, and I don't ever see the defaults in `meteor mongo`. Maybe 
I'm doing something stupid--I've been looking at this for hours and am 
about to take a break. :)

Thanks.

**Comment by jagi** [comment] 2016-02-13 10:11
You have several errors in this example, however here is a code that will work:
```js
Widget1 = Astro.Class({
  name: "Widget1",
  collection: new Mongo.Collection("widgets1"),
  fields: {
    embedded: {
      type: "object",
      nested: {
        name: "Embedded1",
        fields: {
          value: {
            type: "boolean",
            default: true
          }
        }
      },
			default: function() {
				return {};
			}
    }
  }
});

Meteor.startup(() => {
	if (Meteor.isServer) {
		Widget1.remove({});
		let w1 = new Widget1();
	  w1.save();
	}
});
```

**Comment by jagi** [comment] 2016-02-24 23:44
Closing this issue because the fixed code works. If it's still not working for you let me know.

**Closed by jagi** 2016-02-24 23:44 UTC
