### ISSUE TITLE
Cast values

### ISSUE THREAD

**Issue by s7dhansh** [jagi/meteor-astronomy#373] opened 2016-05-06 06:05 UTC
Sadly, jquery .val() gives us String for any type of input. It would be nice if there would be a basic autofix option available which if set to true, would try to "fix" the value of field.

eg. 

```
age: {
 type: Number,
 autofix: true,
}
```

Now in forms even if we get string data from number inputs, it will be converted and validated. Ditto for date libraries.

For now, I plan to use a function built on top of Class.getFields. But this sure could be a useful feature. What say @jagi ?

**Comment by lukejagodzinski** [comment] 2016-05-06 06:13
Yes, this feature is planned for version 2.1. It will probably introduce the `fromForm()` method (or similar name) that will perform casting. Moreover it will be possible to provide casting function for each field.

**Comment by s7dhansh** [comment] 2016-05-06 06:15
Oh great!

**Comment by talha-asad** [comment] 2016-07-21 06:38
@jagi let's get this resolved. I'd like to contribute. Generally most of the data comes from forms and casting each and every date and number can be very cumbersome.

**Comment by s7dhansh** [comment] 2016-07-21 06:41
Yes.. I can also help

**Comment by lukejagodzinski** [comment] 2016-07-21 07:13
PRs are welcome :)

**Comment by s7dhansh** [comment] 2016-07-21 07:14
But can you point us in the right direction. The code base is decently big to sift through :)

**Comment by talha-asad** [comment] 2016-07-21 07:25
I am guessing this is going to be implemented in the fields module. What is the interface we should aim for, @jagi can you give some samples of how you envision the interface for this?

**Comment by lukejagodzinski** [comment] 2016-07-21 07:38
Yes sure I will give you some instructions later today

**Comment by lukejagodzinski** [comment] 2016-07-21 18:54
Originally I was thinking about some method that would take form element.

``` js
doc.setWithForm(form);
```

Could be some other name. It could be just the `set()` method that would detect if an argument is a form element.
The `setWithForm` method could look like this

``` js
setWithForm(form) {
  const Class = this.constructor;
  const inputs = form.querySelectorAll('textarea, input, select'); // Just get all inputs
  _.each(inputs, (input) => {
    // Try getting field with a given input name
    // We should also get somehow nested fields if a field name is in form `fieldName.nestedFieldName`
    const field = Class.getField(input.name);
    if (field) {
      // Get input value
      const value = input.value;
      // Method that would call `field.type.cast()` method that should covert value to the given type.
      const castedValue = field.cast(value);
      doc.set(field.name, castedValue);
    }
  });
}
```

Moreover we could also allow setting single field.

``` js
doc.set(fieldName, fieldValue, {cast: true});
```

So it could be just the set method that would behave differently depending on situation.

``` js
// 1
doc.set(form, {cast: true});
// 2
const values = getAllValuesFromForm(form);
doc.set(values, {cast: true});
// 3
doc.set(fieldName, fieldValue, {cast: true});
```

What do you think?

**Comment by s7dhansh** [comment] 2016-07-21 20:14
I think we should leave the form out of astronomy and let it focus on just the values. So IMO, let's skip 1 and do 2 and 3.
1. Should we keep cast as true by default?
2. Should we do this on set, or on validate/save?

**Comment by lukejagodzinski** [comment] 2016-07-21 22:27
Yes I agree that we should probably leave retrieving values from the form to developer. It's quite easy with jQuery to get values of all fields in a form.
1. Not in 2.0 as it would be compatibility breaking change.
2. It should only be done on set with the `set()` method. User should explicitly request casting.

**Comment by s7dhansh** [comment] 2016-07-23 04:01
1. Ok, explicit is fine. But doing it only on set makes it tedious again.  We should have an option of doing it on validate/save as well.

**Comment by talha-asad** [comment] 2016-07-23 04:05
A field in schema should be able to set autoCast to true. We should be able to set a cast function. If a field has autoCast set to true it should be autocasted using set or =.  By default autocast should be false for backwards compatibility and to avoid unexpected behavior.

Thoughts?

**Comment by s7dhansh** [comment] 2016-07-23 04:45
@talha-asad seems good. but still, IMO we should have that explicit cast option. It will ensure that while we can have our schema relatively safer, we can do the casting on fly if needed.

**Comment by talha-asad** [comment] 2016-08-01 07:06
Sorry guys, I was on vacations.

How does this look:
1. A field will have the ability to set `autoCast: true`, which will automatically cast the value. This will be explicitly set in the schema and will work when the value is being set using `set` or `=`.
2. While setting a value for a field using `set` the user can explicitly request the value to be casted by setting `cast` to true in the third parameter object.
3. A field will have the ability to provide a `cast` function which will be used to cast a value, by default Astro can have default cast functions for primitive types.

**Comment by lukejagodzinski** [comment] 2016-08-01 08:15
@talha-asad I agree but it won't cast values on assignments `=`. I would also name this option just `cast: true`

**Comment by s7dhansh** [comment] 2016-08-02 12:05
@talha-asad looks fine. why don't we have a common field, named `cast` as @jagi suggests, which may be either `true` or a function. if `true`, it will be casted using JS/Astronomy cast operators, else using the given function.
Additionally, if in some case we do not want to cast a field, that's set to auto cast, we should specify `{cast: false}` in `set`.

@jagi which file do these implementations go into?
also, can we not implement a casting on `=`? That would be quite cool. I hardly use set anymore.

**Comment by talha-asad** [comment] 2016-08-02 13:16
@s7dhansh I like the last proposed implementation.

@jagi cast and autocast, are 2 separate concerns that need to be addressed. Otherwise it'll be the same problem we had in v1.

I think the implementation of these will mostly go into the fields module in astronomy. Would like to hear jagi's opinion on this.

**Comment by lukejagodzinski** [comment] 2016-08-02 13:17
@talha-asad What's the difference between cast and autocast?

**Comment by talha-asad** [comment] 2016-08-02 13:48
**Cast**
You can have a field that has a cast function, but it doesn't get casted until casting is explicitly requested. The default still remains to not cast. You can for example set a field's value to an already casted value.

**Autocast**
With this set to true, the default behavior becomes to cast all values and you would be explicitly requesting to not cast a value, in case it is already casted.

These could be combined by perhaps using a boolean value for `cast` property(schema) and inferring it as autocast and a function in case of a custom casting function. However then it won't be possible to setup a field as autocastable and use a custom function at the same time.

**Comment by lukejagodzinski** [comment] 2016-08-02 14:00
@talha-asad still don't understand difference. Can you give some example?

**Comment by talha-asad** [comment] 2016-08-04 07:52
I think I can break it down to a more simpler explaination.
1. If we only have `cast` property in the schema, we can either set it to true/false or a function. Where it could be treated as whether to automatically cast values or to use the custom function for casting, but we will not be able to do both, e.g: use a custom function for casting and automatically cast all values.
2. If we have say a `cast` and a `castFunction` property we can pretty much do whatever we want, I was trying to solve this problem with `autoCast` property, but I can see now how that might become confusing.

Thoughts?

**Comment by s7dhansh** [comment] 2016-08-04 08:03
@talha-asad hmm, that is why i suggested a single `cast`. If it has a function or `true` value, it will ensure automatic casting.
Now, if we want to disable the automatic casting, we will use `{cast: false}` during `set`. IMO this is a cleaner approach.

**Comment by lukejagodzinski** [comment] 2016-08-04 08:41
@talha-asad @s7dhansh sorry guys but I still don't understand clearly your idea. First of all there will be no automatic casting. Developer has to explicitly tell Astronomy to cast values.

Here is how you provide casting function:

``` js
const Post = Class.create({
  name: 'Post',
  collection: Posts,
  fields: {
    publishedAt: {
      type: Date,
      cast(value) {
        var n = Number('123');
        if (_.isNumber(n)) {
          return new Date(value);
        }
      }
    }
  }
});
```

And here is how you explicitly tell Astronomy to cast values:

``` js
const post = new Post();
post.set('publishedAt', 1470300039567, {cast: true});
```

**Comment by talha-asad** [comment] 2016-08-04 08:48
@s7dhansh Agreed, much cleaner and simpler.

@jagi As of right now, Astro v2 has no casting. We are proposing once our changes get merged, if a field has the `cast` property set to true or has a function, Astro will start casting that field's value automatically (using `=` or `set`). This will keep it backwards compatible and enable opt-in functionality.

**Comment by s7dhansh** [comment] 2016-08-04 08:49
@jagi what are the problems with automatic casting with `set`? which brings to my previous question, can we not implement a casting on =?

is there a logical challenge in both the above cases (based on how Astronomy is designed), or is it ideological?

**Comment by lukejagodzinski** [comment] 2016-08-04 09:05
There are many subtle things that have to be taken into account.

1) When casting should happen? Should it happen during assignment with `set` or `=`?

The problem with `=` is that it requires defining setters with the `defineProperty` method. Omitting problem of browser support for setters, it's still not possible to cast on assignment using `=`. That's because of how setters work in JS. You can't just define setter function for the field with the same name. That's why in Astronomy v1 I've solved it by storing values in private `_values` object. Which caused even more problems. So forget about `=` assignment casting.

2) If we don't cast during assignment so may cast it on save operation. That would be much easier to do but it also has some cons. When we do:

``` js
post.publishedAt = 123;
// or
post.set('publishedAt', 123);
```

where in the schema we have something that you proposed

``` js
const Post = Class.create({
  name: 'Post',
  collection: Posts,
  fields: {
    publishedAt: {
      type: Date,
      cast: true // Automatically cast values on save using default cast function
    }
  }
});
```

It would just store number `123` in a field. But during the save operation `post.save()` it would cast all values and save the doc. Cons? If you want to have casted value before saving, then it would not be available. Of course casting could happen before the `beforeSave` event is triggered. So in the event values would be casted.

So, as you see it's not so trivial as it seems to be. I would rather lean towards the second solution but with extra `cast` option in the `set` method, so it would force casting before saving.

**Comment by s7dhansh** [comment] 2016-08-05 03:47
Ok. 
So can we implement that second option with `cast: true` in `post.save`, so that even if cast is not mentioned in set, the values are casted on save. It will remove the need to explicitly casting each  value, and help in cases when we are just copying the serialized form data to the doc.

**Comment by talha-asad** [comment] 2016-08-05 04:07
We'll need to have `cast: true` for new document initialization, field value setting using `.set`, and `.save`

**Comment by talha-asad** [comment] 2016-08-05 04:08
> The problem with = is that it requires defining setters with the defineProperty method. Omitting problem of browser support for setters, it's still not possible to cast on assignment using =. That's because of how setters work in JS. You can't just define setter function for the field with the same name. That's why in Astronomy v1 I've solved it by storing values in private _values object. Which caused even more problems. So forget about = assignment casting.

Where are the field values stored in V2? Keeping in mind that the setter function cannot have the same name as a the field name.

**Comment by lukejagodzinski** [comment] 2016-08-05 08:27
Yes we can also have the `cast` option in the document constructor so it would work the same way as `set`. As I think more about it I tend to agree more that we probably should have two properties `cast` (which stands for `autoCast`) and `castFunction`. By default all fields would have the `cast` parameter set to `false` so it would be backward compatible. But if developer wants to cast values for each `save`, `set` and construction operation then he/she should set the `cast` parameter for such fields and it would not require passing the `cast` param to the `set` method etc. However it would still be possible to turn it off for a given set operation.

It's getting a lot more complex right now but maybe it would make everyone happy.

**Comment by lukejagodzinski** [comment] 2016-10-27 10:46
I'm closing this thread as I've created separate one for 2.3.0 version which will come with casting feature https://github.com/jagi/meteor-astronomy/issues/524

**Closed as completed by lukejagodzinski** 2016-10-27 10:46 UTC
Labels: feature, v2
