### ISSUE TITLE
Doesn't work in IE10?

### ISSUE THREAD

**Issue by ffxsam** [jagi/meteor-astronomy#563] opened 2016-12-12 22:24 UTC
I have a feeling the answer is no, but does Astronomy work in IE10? I'm getting the following error:

```
SCRIPT438: Object doesn't support property or method 'getName' 
jagi_astronomy.js, line 132 character 5
```

**Comment by lukejagodzinski** [comment] 2016-12-13 00:17
I'm not sure. IE is always pain in the ass. Babel is supporting IE10 but with some [caveats](https://babeljs.io/docs/usage/caveats/). I'm using ES classes extensively in Astronomy so I assume that it may not work properly. I can't even test as I'm not using Windows and don't have machine running it. If you could give me more detailed error with stack trace then maybe I will be able to tell more.

**Comment by arggh** [comment] 2016-12-14 20:45
@jagi You could download a virtual machine (free of charge and legally) from here: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/#downloads

All you need is VirtualBox or similar to run Windows for testing.

**Comment by lukejagodzinski** [comment] 2016-12-14 21:00
Hehe 3.5 GB to just test on IE... and virtual machines expires after 90 days? WTF? I still don't understand why somebody is creating a browser only for one operating system. I will download it and test anyway but it's pain in the ass. That's why most developers don't support IE at all. And the same scenario will happen with Edge...

**Comment by arggh** [comment] 2016-12-14 21:02
I feel your pain :) If it makes you feel any better, I'm currently carrying 7 different laptops with me. Three of them have Windows. That's not comfortable either!

**Comment by ffxsam** [comment] 2016-12-14 21:04
@jagi I'm not sure what kind of web work you do, but for me personally, using VMware Fusion + Microsoft's virtual machines has been totally invaluable. I have to support other OS+browser combinations (Win Firefox, Win Chrome, IE11, Edge). VirtualBox is ok, IMO, though the emulation is not nearly as good as VMware Fusion.

As far as the expiration: you just make a snapshot after installing the VM. If the OS expires, you just revert to the snapshot.

BTW, don't feel like you need to test on IE10. We've decided to drop support for it, so no worries. 😉  Astronomy works great with IE11.

**Comment by lukejagodzinski** [comment] 2016-12-14 21:04
@arggh 7 different laptops?! :) You must have big backpack for them :)

**Comment by arggh** [comment] 2016-12-14 21:05
I have a car, luckily!

**Comment by lukejagodzinski** [comment] 2016-12-14 21:07
@ffxsam I've been using Parallels trial for a while on Mac and it worked great but it's unfortunately paid. And I don't need Windows so often to buy license :). I will test it out of curiosity :) but fixing it would probably be impossible if a cause of the problem is what I think it is.

**Comment by lukejagodzinski** [comment] 2016-12-14 21:08
@arggh hehe :) it's still quite heavy package to carry :)

**Comment by ffxsam** [comment] 2016-12-14 21:09
Yeah, I wouldn't worry about it. Actually, IE9 and IE11 are more popular than IE10. And no modern web dev cares much about IE9, so..

![giphy](https://cloud.githubusercontent.com/assets/12532733/21201123/937911c0-c1fe-11e6-8854-13a7ab7ee197.gif)

**Comment by lukejagodzinski** [comment] 2017-01-11 19:00
I've been playing around with IE10 for a while and supporting it is very hard to do at this point. There are babel plugins that may solve some problems but it's not perfect. I think it's not worth doing. I would have to spend a lot of time to support browser that should be killed many time ago, like Android 2.2 :P. We just have to wait until people will stop using IE at all... Closing this issue for now

**Closed as completed by lukejagodzinski** 2017-01-11 19:00 UTC
