### ISSUE TITLE
using future (fibers/future)

### ISSUE THREAD

**Issue by frankapimenta** [jagi/meteor-astronomy#562] opened 2016-12-09 10:26 UTC
Using future in Meteor.methods works fine but when using it in Class.extend({meteorMethods: ...}) does not.
---
modules.js?hash=3e1a2a3…:7810 ## There is an issue with `node-fibers` ##
`/node_modules/fibers/bin/browser-undefined-undefined/fibers.node` is missing.

Try running this to fix the issue: undefined /node_modules/fibers/buildmeteorInstall.node_modules.fibers.fibers.js @ modules.js?hash=3e1a2a3…:7810fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116meteorInstall.node_modules.fibers.future.js @ modules.js?hash=3e1a2a3…:7311fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116addJob @ profiles.js:292astronomyExecute @ astronomyExecute.js:26(anonymous function) @ ddp-client.js?hash=bc32a16…:3973withValue @ meteor.js?hash=e3f53db…:1077apply @ ddp-client.js?hash=bc32a16…:3964callMeteorMethod @ call_meteor_method.js:16applyMethod @ applyMethod.js:27callMethod @ callMethod.js:21submitFormJobForm @ _job_form.js:82eventObj.(anonymous function) @ template.coffee:22(anonymous function) @ blaze.js?hash=983d07a…:3718Template._withTemplateInstanceFunc @ blaze.js?hash=983d07a…:3687(anonymous function) @ blaze.js?hash=983d07a…:3717(anonymous function) @ blaze.js?hash=983d07a…:2560Blaze._withCurrentView @ blaze.js?hash=983d07a…:2214(anonymous function) @ blaze.js?hash=983d07a…:2559(anonymous function) @ blaze.js?hash=983d07a…:835dispatch @ jquery.js?hash=c57b3cf…:4723elemData.handle @ jquery.js?hash=c57b3cf…:4391
ddp-client.js?hash=bc32a16…:4007 Uncaught Error: Missing binary. See message above.(…)
---

any idea?

**Comment by lukejagodzinski** [comment] 2016-12-09 11:01
Code example needed

**Comment by frankapimenta** [comment] 2016-12-09 11:23
```javascript
Profile.extend({
  meteorMethods: {
    addPost(title, content, tags, publish) {
      const Future = require('fibers/future');
      let future = new Future();

      const post = new Post({profileId: this._id, title: title, content: content, tags: tags, publish: publish});
      post.validate((err) => {
        if(err) {
          future.throw(new Meteor.Error('profile-add-post-invalid-data', "provide valid data to add new post"));
        } else {
          post.save((err, result) => {
            if(err) {
              future.throw(new Meteor.Error('profile-add-post-not-saved', "could not save post, try again later."));
            } else {
              if(result) {
                this.postsIds.push(result);
                this.save((err, res) => {
                  if(err) {
                    future.throw(new Meteor.Error('profile-add-post-not-saved', "could not save post, try again later."));
                  } else {
                    if(res) { future.return(result); }
                  }
                });
              }
            }
          });
        }
      });
      future.wait();
      return future.value;
    }
  }
});
```

**Comment by frankapimenta** [comment] 2016-12-09 16:29
can you confirm the problem?

**Comment by lukejagodzinski** [comment] 2016-12-09 17:21
Can you create reproduction repository so I can clone it and just run?

**Comment by lukejagodzinski** [comment] 2016-12-16 11:50
Closing it until reproduction is prepared

**Closed as completed by lukejagodzinski** 2016-12-16 11:50 UTC
Labels: needs-reproduction, v2

**Comment by frankapimenta** [comment] 2016-12-16 12:20
What I did was to just use features in your meteorMethods methods. Just that. When I remove the futures implementation it works fine.

I changed them to Meteor.methods({}) and now all works fine.

**Comment by lukejagodzinski** [comment] 2016-12-16 13:26
Are you sure that you're not trying to run futures on the client? I've tested your code with some modifications and it worked but it had to be defined only on the server as fibers are not allowed on the client. I've added the following `meteorMethod` to the `User` class from Astronomy example.

```js
if (Meteor.isServer || Meteor.isClient) {
  User.extend({
    meteorMethods: {
      addUser() {
        const Future = require('fibers/future');
        let future = new Future();

        const user = new User({
          firstName: 'John',
          lastName: 'Smith',
          email: 'john.smith@gmail.com',
          birthDate: new Date(1980, 1, 1),
          address: {
            city: 'San Francisco',
            state: 'CA'
          }
        });
        user.validate((err) => {
          if (err) {
            future.throw(new Meteor.Error(
              'profile-add-user-invalid-data',
              "provide valid data to add new user")
            );
          }
          else {
            user.save((err, result) => {
              if (err) {
                future.throw(new Meteor.Error(
                  'profile-add-user-not-saved',
                  "could not save user, try again later.")
                );
              }
              else {
                future.return(result);
              }
            });
          }
        });
        future.wait();
        return future.value;
      }
    }
  });
}
```

```js
const user = new User();
user.callMethod('addUser');
```

**Comment by frankapimenta** [comment] 2016-12-16 15:26
aren't the methods defined in <class>.extend({meteorMethods: ...}) only server methods? then you call it from the client and it is ok...right? am I confusing something here?

without your if in the beginning what I do is basically that....

then i do call the following on the client (in a form event):

```javascript
const user = new User();
user.callMethod('addUser');

```

**Comment by lukejagodzinski** [comment] 2016-12-16 15:55
@frankapimenta no, methods are defined both on the client and server the same as `Meteor.methods`. It's developer's responsibility to limit method definition to only one desired environment.

**Comment by lukejagodzinski** [comment] 2016-12-16 16:03
@frankapimenta I also don't understand why you're using fibers/future when you can just use try catch blocks:

```js
Profile.extend({
  meteorMethods: {
    addPost(title, content, tags, publish) {
      const post = new Post({
        profileId: this._id,
        title: title,
        content: content,
        tags: tags,
        publish: publish
      });
      try {
        post.validate();
      }
      catch(err) {
        throw new Meteor.Error(
          'profile-add-post-invalid-data',
          "provide valid data to add new post"
        );
      }
      let result;
      try {
        result = post.save();
      }
      catch(err) {
        throw new Meteor.Error(
          'profile-add-post-not-saved',
          "could not save post, try again later."
        );
      }
      this.postsIds.push(result);
      try {
        return this.save();
      }
      catch(err) {
        throw new Meteor.Error(
          'profile-add-post-not-saved',
          "could not save post, try again later."
        );
      }
    }
  }
});
```

It's much more readable and you avoid callbacks hell.

**Comment by frankapimenta** [comment] 2016-12-16 16:04
I looked at you docs and this time I notice this comment: // server.js in
```javascript
// server.js
User.extend({
  meteorMethods: {
    rename(firstName, lastName) {
      this.firstName = firstName;
      this.lastName = lastName;
      return this.save();
    }
  }
});
```

So the file has to be defined in server side folder (one of the ways) as my meteor methods are (in a server folder).
I thought you did that limitation yourself in the library. It was what made sense to me.

I know now how to solve it, I just move it to a server folder file.

Said this: yes fibers were being called in the client.

Why don't you define your meteorMethods server side only and this way we don't move code to a different file?

**Comment by frankapimenta** [comment] 2016-12-16 16:08
regarding the callback hell I'm with you. you are totally right.
I thought of using try catch blocks but I was very interested in finding out why the thing with the futures was not working.

does it make sense to somehow have a way to make your meteorMethods in extending class only server methods?

**Comment by lukejagodzinski** [comment] 2016-12-16 16:08
Because you may want to have both client & server methods the same way as it's possible in Meteor. You can also define client side only methods.

**Comment by frankapimenta** [comment] 2016-12-16 16:11
ok. why not to have a option such:

```javascript
meteorMethods: {
  server: {
    addUser() {...}
  }
}
```

?

**Comment by lukejagodzinski** [comment] 2016-12-16 16:12
Everything is described in documentation in, I think, security section. You will have to define meteorMethods server only if you want to hide some logic from the user and if you want to perform some permissions check on the server. "Never trust the client" - is the commonly known philosophy. You always have to secure your application server side. Client side methods are only for latency compensation (client simulation). Sometimes you may use client only methods if your code is only designed to work with client data.

**Comment by lukejagodzinski** [comment] 2016-12-16 16:16
@frankapimenta because it would be ugly API. MDG not without reason introduced `Meteor.isClient` and `Meteor.isServer` properties. You can also put your code in the server only files. Meteor and Astronomy is very flexible in that manner. You can do it in many ways:

```js
// server/server.js file
Profile.extend({
  meteorMethods: {
    addUser() { /* ... */ }
  }
});
```

```js
// both.js file
if (Meteor.isServer) {
  Profile.extend({
    meteorMethods: {
      addUser() { /* ... */ }
    }
  });
}
```

```js
// both.js file
Profile = Class.create({
  name: 'Profile',
  /* ... */
  meteorMethods: {
    addUser() {
      if (Meteor.isServer) { /* ... */ }
      else { /* ... */ }
    }
  }
});
```

**Comment by lukejagodzinski** [comment] 2016-12-16 16:17
However if you want to hide application logic it's always the best to put your code in the server only files.

**Comment by frankapimenta** [comment] 2016-12-16 16:28
first of all thank you for the fast and current feedback. it is very nice of you.

What I do is to define all methods to create documents as server side methods.
So if I want to create profiles I have a 'profiles/create' server side method only and I call it on the client.
If I want to change the rating of the profile I would use

```javascript
  // in an events method of a template
  
  const profile = Profile.findOne(<an id>);
  profile.changeRating(<newRating>);

```

  when

```javascript
Profile.extend({ // both sides
  changeRating(newRating) {
    this.rating = newRating; 
    return this.save();
  }
});
```

**Comment by frankapimenta** [comment] 2016-12-16 16:38
back to the 

```javascript
meteorMethods: {
  server: {
    addUser() {...}
  }
  client: {
  }
  ...other methods
}
```

if we would have this we would not have to split code of astronomy class in different files.

**Comment by lukejagodzinski** [comment] 2016-12-16 17:18
As I said it's bad API design. As you can't that way hide your server side code from the user. Methods you've showed here are actually safe for being called on the client too. There is nothing special about them. However, security should be implemented as well.

**Comment by frankapimenta** [comment] 2016-12-16 17:31
Yes. True. The code would be available in the client...this would then make no sense at all.
I am sorry about insisting in this suggestion...

**Comment by lukejagodzinski** [comment] 2016-12-16 17:35
No problem. I'm going to create video tutorials next week about Astronomy and security will be a separate video. Video is IMHO better than documentation and it will be a good source of knowledge.

**Comment by frankapimenta** [comment] 2016-12-16 18:01
That is great. Looking forward to it!
You documentation is very good. But I think that one can notice that it is very based on the knowledge you have of your lib and people from outside need to get into ("your mind") and this makes it a bit less fast to follow thru. 

Keep up with the good work. Your library is great!

**Comment by lukejagodzinski** [comment] 2016-12-17 09:58
Yes I know it. It's very common thing when author of documentation is the same person as creator of library. I've seen this problem in many documentation for other libraries. I hope video will explain better my point of view on how to do some stuff.
