### ISSUE TITLE
Strange warnings in 1.0.0-rc.2

### ISSUE THREAD

**Issue by Deadly0** [jagi/meteor-astronomy#100] opened 2015-09-19 19:54 UTC
Have installed new version of Astronomy and got a lot of warnings in console:

![err](https://cloud.githubusercontent.com/assets/4887213/9977897/bc14ae10-5f20-11e5-912f-a64e207cd8ca.png)

My model:
```
@Event = Astro.Class
	name: 'Event'
	collection: Events
	methods: methods
	fields: [
		'externalId'
		'leagueId'
		'state'
		'startDate'
		'homeTeam'
		'awayTeam'
	]
```

Also have another models with the same warning.

**Comment by jagi** [comment] 2015-09-19 20:39
It's warning telling that you are trying to (probably) fetch a document that does not much fields defined in the class. However, you warnings looks strange because it's trying to set _private properties. It looks like you have them saved in the collection as a "EJSONified" object instead a plain JSON object. Please check how your records in the collection look like:

```sh
meteor mongo
db.events.findOne();
```

Paste here what you get

**Comment by Deadly0** [comment] 2015-09-19 21:15
@jagi No, my db data is alright. Looks like that problem with [angular-meteor](https://atmospherejs.com/meteor/angular) package compatibility. Angular trying to synchronize documents between client and server, but don't know that model have some special fields. Did you test your package with angular-meteor?

**Comment by jagi** [comment] 2015-09-19 21:40
No I haven't been testing it with Angular (I don't like Angular :P). Hmm it official package and it would be strange if they synchronise documents between client and server not using DDP. So maybe it's a problem with something else. Could you create some minimal reproduction repository so I could test it?

**Comment by Deadly0** [comment] 2015-09-20 13:24
I've done more deep research and found that this bug not with angular, but with another popular package [publish-composite](https://atmospherejs.com/reywood/publish-composite).
[Repo](https://bitbucket.org/Deadly0/meteor-astronomy-bug) to reproduce the bug.

**Comment by jagi** [comment] 2015-09-20 15:09
Ok I will take a look at it

**Comment by Deadly0** [comment] 2015-09-20 16:09
@jagi, Thanks, but there is a quick solution to disable warning in astronomy? It pushes a lot of warnings in console and it's tough to find anything in it.

**Comment by jagi** [comment] 2015-09-20 19:31
Hmmm, possibility of turning off warnings is a good idea. I will add it to the tasks list

**Comment by jagi** [comment] 2015-09-21 21:21
I've added possibility to turn off warnings `Astro.config.verbose = false;`. Didn't have time yet to check your reproduction repository. Maybe tomorrow I will take a look at it. Stay tuned.

**Comment by Deadly0** [comment] 2015-09-21 23:07
Thank you for workaround. I trust you will find real problem.

**Comment by jagi** [comment] 2015-09-22 10:15
Ok I know what's the problem. You have to modify your `main.js` file to:

```js
Meteor.publishComposite('posts', {
	find: function() {
		return Posts.find({}, {
			transform: null
		})
	}
});
```

You have to publish plain JavaScript objects, so you have to pass `transform: null` as an option of the `find` method. I will add this info to the documentation.

However, I will create my own publishing function that will be part of the relations module. I will allow publishing entire document with relations. It will be event easier than using `publish-composite`.

**Closed by jagi** 2015-09-22 10:15 UTC
