### ISSUE TITLE
1.2.7 getModified regression

### ISSUE THREAD

**Issue by marbemac** [jagi/meteor-astronomy#225] opened 2015-12-17 21:16 UTC
We rely on getModified to show a save/undo button if there are changes to the model.

With 1.2.7, getModified doesn't work correctly for nested objects. Consider:

```js
var model = {
    request: {
        method: 'get'
    }
}

// User changes request method on the model
model.set('request.method', 'put');

// Correctly says request has changed
console.log(model.getModified()); // Object {request: Class}

// User changes request method back
model.set('request.method', 'get');

// incorrectly says request is still modified, even though it is no longer different
console.log(model.getModified()); // Object {request: Class}
```

**Comment by marbemac** [comment] 2015-12-17 21:26
In fact, model "dirty tracking" in general seems to have issues in 1.2.7.

**Comment by jagi** [comment] 2015-12-17 23:08
Can you create a reproduction?

When introducing 1.2.7 version I was expecting to get several issues about the `getModified` method and the `_original` property. It makes Astronomy much faster but changes a few things internally. I've tried to make as much backward compatible as possible. If I won't be able to fix it I would suggest forcing 1.2.6 version in your project. But let's just create reproduction and maybe I will be able to help.

**Comment by jagi** [comment] 2015-12-19 21:13
I've improved backward compatibility in Astronomy 1.2.8. You shouldn't have problem right now.

**Comment by marbemac** [comment] 2015-12-20 20:08
I've updated my astronomy perf repo to demonstrate the bug:

https://github.com/marbemac/astronomy-perf

Load that meteor app up, then change the url in the input field. You'll see getModified() returns the entire request object, which is the first kind of weird thing.

Then, when you clear the input, isModified() correctly returns false, but getModified() still returns the request object, even though nothing in there is actually modified.

**Comment by jagi** [comment] 2015-12-20 21:03
Ok I know what's the problem. The reason that it still sees modifications is because document contains `_modifiers` even if the field's value was set to the original value. I will address that problem tomorrow and publish update. Sorry for breaking backward compatibility but I thought that making Astronomy faster is very important. I think that after that update everything should work as previously and in the same time much faster :)

**Comment by jagi** [comment] 2015-12-22 20:49
Fixed in 1.2.9

**Closed by jagi** 2015-12-22 20:49 UTC
Labels: bug

**Comment by marbemac** [comment] 2015-12-23 14:38
:+1: all good, thanks!

We continue to layer in hacks to work around #156. Any sort of progress update on 2.0? Not a huge rush, just curious.

**Comment by jagi** [comment] 2015-12-23 20:10
I have a little delay with Astronomy 2.0 because of private stuff. Moreover there is Christmas now. So it will be at the beginning of 2016.

What is it about umbrella issue? I don't have time to read entire discussion.

**Comment by marbemac** [comment] 2015-12-23 20:51
No problem on 2016.

I was just suggesting that it might make sense to create an umbrella issue for astronomy 2.0, similar to that linked issue. It's not strictly necessary - just helps people that are interested, follow the 2.0 progress without having to ask or bug you :).

**Comment by jagi** [comment] 2015-12-23 21:45
Oh I see. I didn't know that we can use the "umbrella" word in such situation :). Is there some reason that they use the "umbrella" word instead of something else? :)

Yes I think it's good idea to create such issue. I will do it.

**Comment by marbemac** [comment] 2015-12-29 22:47
I hate to resurrect this again, but see the attached screenshot. I'm not sure exactly what is causing this to happen, but I'm seeing cases where getModified returns an empty object, but isModified() returns true. In the specific case I'm running into, there should be no modifications to the model (so getModified is working correctly, but isModified seems to have an issue).

<img width="648" alt="screen shot 2015-12-29 at 5 45 07 pm" src="https://cloud.githubusercontent.com/assets/847542/12043546/f8ed0652-ae53-11e5-98cd-edcb252fa516.png">

I'll try and figure out how to reproduce this, but in general, should isModified ever return true if getModified returns an empty object?

**Comment by marbemac** [comment] 2015-12-29 22:57
(this does not occur in 1.2.6)

**Comment by jagi** [comment] 2015-12-30 14:34
Ok I will take a look at it

**Comment by talha-asad** [comment] 2016-01-05 09:05
@jagi They use the "umbrella" word because it kind of covers the entire thing. So like how an umbrella covers a person from rain in entirety.
